# Generated by Django 2.2.5 on 2020-05-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quant',
        ),
    ]
